apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
      tier: db
  template:
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec:
      containers:
      - name: mysql-server
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
          - "--explicit_defaults_for_timestamp=1"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
